#+TITLE: esn
#+OPTIONS: toc:nil
#+HTML_HEAD: <style type="text/css">body{ max-width:30%; }</style>

* Implementere evaluering
** "Goodness"
*** Kernel quality/rank (KQ)
*** Generalization
*** Short-term linear memory (MC)
** Dataset
*** NARMA 10/30th order
*** Mackey-Glass
*** Santa Fe laser
*** etc.

  Jeg tenker jeg har ganske god kontroll på disse, og tror jeg kan velge å bruke
  det som er passende fra eksperiment til eksperiment (eksempelvis ved å
  utforske KQ+MC-rommet til topologier, og så forsøke tidsserier med en
  trade-off som ser god ut?).

** Andre muligens interessante målestokker
*** Kolmogorovkompleksitet
  «Kolmogorov’s information, Shannon’s entropy, and topological complexity of
  molecules» og «An Introduction to Kolmogorov Complexity and Its
  Applications». Det finnes topologisk kompleksitet, topologisk entropi osv. Mye
  greier her jeg ikke forstår noe som helst av...

*** Grafentropi (Körner o.l.)
*** Euklidsk dimensjon
*** Teori fra komplekse nettverk
  Kanter som krysser, vertex degree, centrality, clustering coefficient, average
  path mellom hjørner osv. Det finnes nok en haug av disse som er mulig å titte
  på, men jeg har ikke funnet noen jeg har definitivt lyst til å se på.

* Forskjellige typer gitter (lattice)
** Bravaisgitter i 2D: oblique, square, hexagonal, primitive/centered rectangular
  F.eks. forsøke alle 5 typer i 2D (crystallographic restriction theorem). Jeg
  tror at det er vel så fornuftig å holde seg i kun 2D her til å begynne
  med. Kan det være nyttig å finne ut noe om hvilke parametere som er viktige
  dersom man er _tvunget_ til å bruke en viss type gitter (f.eks. kvadrat)?
** Ikke-regulære mønster
  F.eks. gradvise forstyrrelser ved å begynne med et kvadratgitter og så "riste"
  noder. Her kan man lage en gradvis overgang til fullstendig tilfeldig
  konnektivitet.
** Er det viktig om kantene av gitteret gjør en "wrap-around"?
  Dette kan være spennende for å utforske. Jeg tenker at det kan være relevant
  mtp. minnekapasitet om alle kanter av gitteret har en definitiv "slutt" slik
  at snøskred nødvendigvis stopper der (men muligens mer relevant i LSM enn
  ESN).
** Størrelse på naboskap
  Hvordan endrer reservoaret seg dersom man gradvis øker naboskapet til hver
  node? F.eks. kan man begynne med kvadratgitter, og så utvide naboskap til å
  også inkludere naboene til naboene osv., slik at man kan øke helt til global
  konnektivitet.
** Andre aktiveringsfunksjoner for noder i gittere
  Bytte ut tanh med andre funksjoner, evt. se på funksjoner som er spesielt
  relevante for physical reservoir computing.
** Dersom naboskap er globalt, hvor mange negative koblinger trengs?
  Dette ser ut til å være viktig, særlig i Waxman. Jo flere inn-kanter, jo
  viktigere er det at noen av dem er negative.

* Modeller for å generere grafer
** Erdos-Renyi
  Dette er den (tilnærmet) vanlige måten å generere tilfeldige ESNs.
** Waxman
  Noder "drysses" i n-dimensjonalt rom, og kanter opprettes med sannsynlighet
  proporsjonalt med avstander. Jeg har en idé om at dette kan utvides til å
  begynne å sammenlignde 2- og 3-dimensjonalt rom, og så gradvis la et økende
  antall noder i 2d også få en tredje dimensjon, og se om det er en stigende
  trend med flere 3d noder. Jeg tror Waxman-modellen kan være _veldig_ nyttig,
  særlig om jeg utvider den til å inkludere denne gradienten. Til slutt tenker
  jeg at det også kan være nyttig å teste forskjellige sannsynlighetsfordelinger
  for kobling av kanter.
** Watts-Strogatz
  Regulære gitter (ofte ring) hvor noen kanter tilfeldig omkobles. Produserer
  "small world"-topologier med lokal clustering. Clustering kan være kult særlig
  f.eks. [[https://yongyeol.com/papers/rodriguez2019optimal.pdf][dette]].
** Andre formelle måter å generere tilfeldige grafer som kan være interessante
  Her kan jeg gjøre mer research for å se om jeg finner noen som kan være
  spennende. Kjapt søk: Barabási-Albert (preferential attachment istedenfor
  small world), samt en håndfull andre artikler hvor en stor andel er relatert
  til sosiale nettverk (tenk Facebook o.l.). Kan være interesant å modellere for
  ESN. Eller ikke -- vanskelig å forutsi!

* Off topic: applikasjon i musikk
  Jeg har tenkt litt på bruk av ESN (eller en RC i det hele tatt, uavhengig av
  reservoar) for å tilnærme musikkeffekter, f.eks. gitarpedaler. Dette er mest
  en kuriositet, men kunne vært interessant å se på ved siden av for moro
  skyld. :-) [[http://citeseerx.ist.psu.edu/viewdoc/download?doi%3D10.1.1.73.7637&rep%3Drep1&type%3Dpdf][Paper]].
